const USER_SESSION_API = {
  get_auth_token: 'auth/get-auth-token',
  send_otp: 'auth/send-otp',
  // send_otp: 'send-otp',
  verify_otp: 'auth/verify-otp',
  verify_email: 'auth/verify-email',
  register: 'auth/register',
  login: 'auth/login',
  // create_edit_profile: 'create-edit-profile',
  update_profile: 'auth/update-profile',
  get_profile: 'auth/profile',
  logout: 'auth/logout',
  delete_account: 'auth/delete-account',
  forgot_password: 'forgot-password',
  reset_password_token: 'auth/reset-password-token',
  // reset_password: 'auth/reset-password',
  update_password: 'auth/update-password',
  // change_password: 'change-password',
  welcome_text: 'welcome-text',
  version_control: 'auth/version-control',
  manage_profile_picture: 'manage-profile-picture',
  delete_avatar: 'auth/delete-avatar',
  blocked_users: 'auth/blocked-users',
   create_report: 'auth/create-report',
  update_fcm_token: 'auth/update-fcm-token',
};
const APP_SESSION_API = {
  upload_chat_media: 'chat/file-upload',
  user_list: 'user-list',
  create_group: 'create-group',
  get_favorite_game: 'profile/get-favorite-game',
  get_game_genre: 'profile/get-game-genre',
  get_game_platform: 'profile/get-game-platform',
  get_game_schedule: 'profile/get-game-schedule',
  get_gender: 'profile/get-gender',
  get_playing_style: 'profile/get-playing-style',
  home_page: 'api/home_page',
  gamer_detail: 'api/gamer-detail',
  like_dislike: 'api/like-dislike',
  browse_gamer_list: 'api/browse-gamer-list',
  pending_interest: 'api/pending-interest',
  pending_request: 'api/pending-request',
  mutual_connection: 'api/mutual-connection',
  notification_list: 'notification/list',
  notification_count: 'notification/notification-count',
  notification_read: 'notification/read',
  in_app_purchase_restore: 'in-app-purchase/restore',
  in_app_purchase: 'in-app-purchase/purchase',
  project_init: 'project/init',
};

export {USER_SESSION_API, APP_SESSION_API};
